services:
  laravel-app:
    build:
        context: '.'
        args:
            uid: ${UID}
    container_name: laravel_iptv
    ports:
        - 8000:80
    environment:
        - APACHE_RUN_USER=#1000
        - APACHE_RUN_GROUP=#1000
    volumes:
        - .:/var/www/html
        - ./database:/var/www/html/database
    networks:
        backend:
            aliases:
                - app
