build:
    nodes:
        php71:
            environment:
                php:
                    version: 7.1
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit'
        php72:
            environment:
                php:
                    version: 7.2
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit'
        php73:
            environment:
                php:
                    version: 7.3
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit'
        php74:
            environment:
                php:
                    version: 7.4
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit'
        php8:
            environment:
                php:
                    version: 8.0
            tests:
                override:
                    -
                        command: 'vendor/bin/phpunit'
