language: php
php:
    - '7.1'
    - '7.2'
    - '7.3'
    - '7.4'
    - '8.0'

env:
  global:
    - PHPUNIT_BIN='vendor/bin/phpunit'
    - PHPUNIT_CONFIG='phpunit.xml'
    - PHPUNIT_FLAGS='--stop-on-failure --verbose'

before_script:
  - composer config --global repo.packagist composer https://packagist.org
  - composer install

script : $PHPUNIT_BIN -c $PHPUNIT_CONFIG $PHPUNIT_FLAGS

after_success:
  - vendor/bin/test-reporter
